server:
  port: 8761

spring:
  application:
    name: its-eureka-server

eureka:
  client:
    register-with-eureka: false   # Server không tự đăng ký chính nó
    fetch-registry: false         # Server không cần fetch danh sách
